---
vfs:
  bus: "pci0000:00/0000:00:02.0"
  count: 4
  kernel: "6.14.8-2-pve"

ksm:
  - option: "KSM_SLEEP_MSEC"
    value: 30
  - option: "KSM_NPAGES_MAX"
    value: 1280
  - option: "KSM_THRES_COEF"
    value: 50

swap:
  swappiness: 20

zramswap:
  algo: lz4
  percent: 15

cpu:
  governor: powersave

rsyslog:
  rsyslog_client_additional_actions: |
    if ($msg contains "Attempting to mount") or
       ($msg contains "enabling forceuid mount option implicitly") or
       ($msg contains "enabling forcegid mount option implicitly") then {
        stop
    }
