---
proxmox_i915_driver_checksum: "sha256:dff94ca92f4b16c18042922fc22983c9ac00581b90a84a6588b67196a3440c1c"
proxmox_i915_driver_dest: "/root/i915-sriov-dkms_2025.12.10_amd64.deb"
proxmox_i915_driver_url: https://github.com/strongtz/i915-sriov-dkms/releases/download/2025.12.10/i915-sriov-dkms_2025.12.10_amd64.deb

proxmox_vfs_bus: "pci0000:00/0000:00:02.0"
proxmox_vfs_count: 4
proxmox_vfs_kernel: "6.14.8-2-pve"

ksm:
  - option: "KSM_SLEEP_MSEC"
    value: 30
  - option: "KSM_NPAGES_MAX"
    value: 1280
  - option: "KSM_THRES_COEF"
    value: 50

swap:
  swappiness: 20

zramswap:
  algo: lz4
  percent: 15

cpu:
  governor: performance

rsyslog:
  rsyslog_client_additional_actions: |
    if ($msg contains "Attempting to mount") or
       ($msg contains "enabling forceuid mount option implicitly") or
       ($msg contains "enabling forcegid mount option implicitly") then {
        stop
    }
