---
apt:
  - dstat
  - htop
  - qemu-guest-agent

services_start:
  - qemu-guest-agent
  - ssh

firewall:
  policy: deny
  allow_rules:
    ipv4:
      - name: "SSH from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '22'
      - name: "DNS from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: "53"
      - name: "DNS(UDP) from service line"
        proto: "udp"
        src: "192.168.88.0/24"
        port: "53"
      - name: "Tailscale WireGuard Tunnel"
        proto: "udp"
        src: "any"
        port: "41641"
      - name: "Tailscale STUN"
        proto: "udp"
        src: "any"
        port: "3478"
    ipv6:
      - name: "DHCPv6 Client from service line"
        proto: "udp"
        src: "::/0"
        port: "546"
      - name: "DHCPv6 Client from service line"
        proto: "udp"
        src: "::/0"
        port: "546"
