zabbix_docker_project_path: "/root/zabbix"
zabbix_nfs_server: 192.168.88.10
zabbix_nfs_export: "/mnt/backup/zabbix_backups"

zabbix_mysql_database: zabbix
zabbix_mysql_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66623566383361373863636331313830633033626631613733643438303234343431393163356634
  6663623338623462386531636634376665383035306130630a383639336262373833393131373532
  36623566646636653930653636636331316661353661376361616238613765366332303833383830
  6464666335656437630a613333383333366561653232646338613165303562666162313633313065
  3832

zabbix_mysql_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32353562333232613631653265656633343962643838393666393964656132653662373563383933
  3535323934626632313735653733386631393330646332630a666463633434323036313761303939
  32663866316132373839356532306537653937336536393934653230613433643630373266653663
  3135653366653931300a633938623735326266393665383231663532383535653233306430663666
  3539
zabbix_mysql_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35343533313236336230343164666333323839633432353936346239363861396262376136626661
  6337383331616136373132313565306331613932353939310a666236323363316562393736613138
  37323266303137393066626162323732353565396337663761356636646137656166653164373863
  3663383634613230360a333534343330623638313839393638306537636533623635663639383131
  6130
