proxmox_i915_driver_checksum: "sha256:e7887156f44a4f24f9f0e49aa93ece1c6658e8fae34a6ab0e414c03db8976511"
proxmox_i915_driver_dest: "/root/i915-sriov-dkms_2026.02.09_amd64.deb"
proxmox_i915_driver_url: https://github.com/strongtz/i915-sriov-dkms/releases/download/2026.02.09/i915-sriov-dkms_2026.02.09_amd64.deb

proxmox_ksm:
  - option: "KSM_SLEEP_MSEC"
    value: 30
  - option: "KSM_NPAGES_MAX"
    value: 1280
  - option: "KSM_THRES_COEF"
    value: 50

proxmox_zramswap_algo: lz4
proxmox_zramswap_percent: 15

proxmox_swappiness: 20

proxmox_cpu:
  governor: performance

# Use common_hostinfo.macaddress
proxmox_macaddr: "00:00:00:00:00:00"
