---
- name: "Disable CoW if btrfs"
  when: docker_btrfs is defined and docker_btrfs
  ansible.builtin.command:
    cmd: chattr +C /var/lib/docker
  register: retval
  changed_when: retval.rc == 0
  notify: "Disable CoW if btrfs"

- name: Restart docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
  listen: "Restart docker"
