---
gui_install:
  chrome: true
  igpu: true
  remmina: true
  vlc: true
  wine: false
  mozc: true
  sushi: true
  firefox: false

gui_supplemental_packages:
  - ffmpeg
  - ffmpegthumbnailer

gui_additional_packages:
