---
- name: "Restart rsyslog.service"
  ansible.builtin.systemd_service:
    name: rsyslog.service
    state: restarted
    enabled: true
  listen: "Restart rsyslog"

- name: "Restart rsyslog.service"
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
    enabled: true
  listen: "Restart journald"
