---
- name: "Start Zabbix Docker Compose"
  community.docker.docker_compose_v2:
    project_src: /root/zabbix/
    state: present
  listen: "Up docker-compose"

- name: "Restart cron"
  ansible.builtin.systemd_service:
    name: cron.service
    state: restarted
    enabled: true
  listen: "Restart cron"
