---
firewall:
  policy: deny
  allow_rules:
    ipv4:
      - name: "SSH from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '22'
      - name: "Scrutiny from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '8080'
      - name: "Zabbix from Zabbix-server"
        proto: "tcp"
        src: "192.168.88.106/24"
        port: "10050"
    ipv6:
      - name: "DHCPv6 Client from service line"
        proto: "udp"
        src: "::"
        port: "546"
docker_network:
  base: "172.17.121.0/24"
  size: "28"

scrutiny:
  mail:
    # Use "%40" instead of "@"
    address: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37626436383563383031623731626632666238653561646266373334653835323235323634363737
          6138393863323835393730656363323164616538346564300a636239306264376664373637356461
          32346531663736386162393663373962376531636161353465386366306532643638613239633361
          3333663266343266620a616338386663373735303665383434386639396533666139313264633162
          65623139313832393739386432393637643030323137306362363739386633313433
    app_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35373561363765326664393633653535613739656533653237636164303264613464353063333065
          6366396134353930666637333837633631323961336631660a393863333439626262366366633966
          61386566656365313961346365613531633762613165363730656464643332306236643264653837
          6563363634626339350a373936353061373931643436356262626261376234393439326464373334
          66633733653962636565326236396464363461336361666431643263373231356566

swappiness: 10
