runners:
  basepath: "/opt/runner"
  runners:
    - runner_name: ecs05
      github_repo: ecs
    - runner_name: periodic_backup_05-01
      github_repo: periodic_backup
    - runner_name: ansible_hayaworld_05-01
      github_repo: ansible_hayaworld

docker_network:
  base: "172.17.5.0/24"
  size: "28"
