runners:
  basepath: "/opt/runner"
  runners:
    - runner_name: ansible_hayaworld_04-01
      github_repo: ansible_hayaworld
    - runner_name: ansible_hayaworld_04-02
      github_repo: ansible_hayaworld
    - runner_name: ansible_hayaworld_04-03
      github_repo: ansible_hayaworld
    - runner_name: ansible_hayaworld_04-04
      github_repo: ansible_hayaworld
    - runner_name: periodic_twitter_dl_04-01
      github_repo: periodic_twitter_dl
    - runner_name: periodic_backup_04-01
      github_repo: periodic_backup
    - runner_name: ecs04
      github_repo: ecs

docker_network:
  base: "172.17.4.0/24"
  size: "28"
