runners:
  basepath: "/opt/runner"
  runners:
    - runner_name: ecs01
      github_repo: ecs
    - runner_name: periodic_backup_01-01
      github_repo: periodic_backup
    - runner_name: ansible_hayaworld_01-01
      github_repo: ansible_hayaworld

docker_network:
  base: "172.17.1.0/24"
  size: "28"
