runners:
  basepath: "/opt/runner"
  runners:
    - runner_name: ect05
      github_repo: ect
    - runner_name: periodic_backup_05-01
      github_repo: periodic_backup
    - runner_name: ansible_hayaworld_05-01
      github_repo: ansible_hayaworld

docker_config:
  default-address-pools:
    - base: "172.17.5.0/24"
      size: 28
