---
firewall:
  policy: deny
  allow_rules:
    ipv4:
      - name: "SSH from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '22'
      - name: "Zabbix Server"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: "10051"
      - name: "Zabbix Agent"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: "10050"
      - name: "Zabbix Web UI"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: "8080"
    ipv6:
      - name: "DHCPv6 Client from service line"
        proto: "udp"
        src: "::"
        port: "546"

docker_config:
  default-address-pools:
    - base: "172.18.3.0/24"
      size: 28
  dns:
    - 192.168.88.100
    - 192.168.88.150

swappiness: 10
