---
graylog_data_root: "/opt/data"
graylog_backup_src: "/mnt/skylark/graylog_dump"
graylog_backup_dest: "/backup"

graylog_project_root: "/root/gl"

graylog_opensearch_initial_admin_password: "none"
# echo -n "password" | sha256sum
graylog_password_secret: "none"
graylog_root_password: "none"
graylog_email_user: "example@example.com"
graylog_email_password: "password"
graylog_email_host: "example.com"

# Dependency Docker Install Vers
docker_edition: 'ce'
docker_packages_state: present
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
