---
name: Hayaworld Ansible Jobs (Deploy)
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  Yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run YAML Lint
        run: yamllint --strict --format github .

  AnsibleLint:
    runs-on: self-hosted
    container:
      image: ghcr.io/ansible/community-ansible-dev-tools:latest
      credentials:
        username: "${{ secrets.GHCR_USERNAME }}"
        password: "${{ secrets.GHCR_PASSWORD }}"
      volumes:
        - ansible-galaxy:/github/home/.ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Galaxy files
        uses: actions/cache/restore@v3
        with:
          key: ansible_galaxy_cache
          path: "/github/home/.ansible"

      - name: Prepare environments (ansible-galaxy install role)
        run: |
          ansible-galaxy role install -r requirements.yml --ignore-errors

      - name: Prepare environments (ansible-galaxy install collection)
        run: |
          ansible-galaxy collection install -r requirements.yml --ignore-errors

      - name: Save Galaxy files
        uses: actions/cache/save@v3
        with:
          key: ansible_galaxy_cache
          path: "/github/home/.ansible"
        if: ${{ always() || cancelled() }}

      - name: Run Ansible-lint
        run: |
          ansible-lint

  Duplicate_Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add exec flag to dupcheck.sh
        run: "chmod +x ./dupcheck.sh"

      - name: NXDOMAIN_Duplicate_Check
        run: >
          "./dupcheck.sh"
          "host_vars/dns/NXDOMAIN.yml"

  Dry_Run_ansible:
    needs:
      - Yamllint
      - AnsibleLint
      - Duplicate_Check
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        vm:
          - dns
    environment: Production
    container:
      image: ghcr.io/ansible/community-ansible-dev-tools:latest
      credentials:
        username: "${{ secrets.GHCR_USERNAME }}"
        password: "${{ secrets.GHCR_PASSWORD }}"
      volumes:
        - /home/runner/.ssh:/root/.ssh:ro
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Restore Galaxy files
        uses: actions/cache/restore@v3
        with:
          key: ansible_galaxy_cache
          path: "/github/home/.ansible"

      - name: Prepare environments (ansible-galaxy install role)
        run: |
          ansible-galaxy role install -r requirements.yml --ignore-errors

      - name: Prepare environments (ansible-galaxy install collection)
        run: |
          ansible-galaxy collection install -r requirements.yml --ignore-errors

      - name: "Prepare Vault Password file"
        run: |
          echo '${{ secrets.VAULT_PASSWORD }}' > ./vault_passwd.txt

      - name: "ansible-playbook -C"
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook \
            -i inventories \
            -C \
            --ssh-extra-args='-o StrictHostKeyChecking=no' \
            --vault-password-file ./vault_passwd.txt \
            --extra-vars "ansible_sudo_pass=${{ secrets.SUDO }}" \
            ${{ matrix.vm }}.yml

  Run_ansible:
    if: "${{ github.ref == 'refs/heads/master'}}"
    needs:
      - Dry_Run_ansible
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        vm:
          - dns
    environment: Production
    container:
      image: ghcr.io/ansible/community-ansible-dev-tools:latest
      volumes:
        - /home/runner/.ssh:/root/.ssh:ro
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Restore Galaxy files
        uses: actions/cache/restore@v3
        with:
          key: ansible_galaxy_cache
          path: "/github/home/.ansible"

      - name: Prepare environments (ansible-galaxy install role)
        run: |
          ansible-galaxy role install -r requirements.yml --ignore-errors

      - name: Prepare environments (ansible-galaxy install collection)
        run: |
          ansible-galaxy collection install -r requirements.yml --ignore-errors

      - name: "Prepare Vault Password file"
        run: |
          echo '${{ secrets.VAULT_PASSWORD }}' > ./vault_passwd.txt

      - name: "Run ansible-playbook"
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook \
            -i inventories \
            --ssh-extra-args='-o StrictHostKeyChecking=no' \
            --vault-password-file ./vault_passwd.txt \
            --extra-vars "ansible_sudo_pass=${{ secrets.SUDO }}" \
            ${{ matrix.vm }}.yml
